# @package _global_
task:
  name: retrain
  stage: "08_retrain"
  project_name: "${run.clearml.project_root}/TabularAnalysis/${run.usecase_id}/08_retrain"

retrain:
  dataset_path: ${data.dataset_path}
  dataset_id: ${data.raw_dataset_id}
