# @package _global_
task:
  name: pipeline
  stage: "99_pipeline"
  project_name: "${run.clearml.project_root}/TabularAnalysis/${run.usecase_id}/99_pipeline"

pipeline:
  run_dataset_register: true
  run_preprocess: true
  run_train: true
  run_leaderboard: true
  run_infer: false
  plan_only: false

  grid:
    preprocess_variants: [stdscaler_ohe]
    model_variants: [ridge]
    max_jobs: ${exec_policy.limits.max_jobs}

  hpo:
    enabled: false
    params:
      ridge:
        alpha: [0.1, 1.0, 10.0]
